### ISSUE TITLE
Fixes for PHP 8 compatibility

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/UKBMS#32]
@BirenRathod @DavidRoy
The fixes for PHP 8 have been deployed to live.

Note: I noticed the following options were off. I have switched them on which may possibly help a little with some of the performance issues that have recently been reported with the site.
Aggregate CSS files
Aggregate JavaScript files 

Fixes include (but not be limited to).
- iForm, Client Helpers, Media, Indicia_Features updated to latest version (exlcuding UKBMS specific forms which are out of date in the indicia-team repositories, this is on my task list to rectify)
- Fixed problems reported by Ian Middlebrook.
Incorrect aattribute ordering on Site Details.
Reporting area giving fatal errors.
All sites having problems with column widths forcing the Edit link off side of screen.

Note the PHP 8 Pantheon.yml file had the PHP 8 line removed, so live is running 7 still awaiting Biren to upgrade when he is ready.

**Comment by BirenRathod** [comment]
Thanks, @andrewvanbreda. If you can respond to other email, so everybody will be aware of it.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Not sure which email. I have messaged Ian Middlebrook to say we were going live, David knows.
So am not sure who else need to be in loop with this.
@Gary-van-Breda @kazlauskis note this has gone live on UKBMS in case it affects you.

**Comment by BirenRathod** [comment]
@andrewvanbreda That means, you updated PHP 8-related code on all sites now including ebms too?

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
They are ready for me to merge but not all merged to live yet. So I am going to do EBMS, UKPoMS today.

I cannot do SPRING today I am afraid as David is demoing it, however it is ready, so I can merge that tomorrow

NPMS, Plant Portal, Fit Count, UKBMS are done and live.
